source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'json'
gem 'mongo'
gem 'bson_ext'
gem 'faraday'
gem 'xml-simple'
gem 'jsmin'
gem 'cssmin'
gem 'msg', :git => 'http://git.vibes.com/msg-gem.git'
